//=========================================================
// File: arbiter_if.sv
//
// Common interface used for BOTH:
//   1. Fixed-priority arbiter
//   2. Round-robin arbiter
//
// req and grant are used by both DUTs.
//
// clk and reset are required by the round-robin arbiter.
// They remain present for the fixed-priority environment
// so that the same UVM driver and monitor can be reused.
//
// SystemVerilog Assertions (SVA) are included directly
// in the interface so that protocol/property checking is
// centralized for both arbiters.
//=========================================================

interface arbiter_if(input logic clk);

    //=====================================================
    // INTERFACE SIGNALS
    //=====================================================

    // Reset signal
    //
    // Used by the round-robin arbiter.
    // The fixed-priority arbiter is combinational, but
    // reset remains part of the common interface.
    logic reset;


    // Request vector
    //
    // req[0] -> Requester 0
    // req[1] -> Requester 1
    // req[2] -> Requester 2
    // req[3] -> Requester 3
    logic [3:0] req;


    // Grant vector generated by the DUT.
    //
    // Legal grant values:
    //
    // 0000 -> No requester granted
    // 0001 -> Requester 0 granted
    // 0010 -> Requester 1 granted
    // 0100 -> Requester 2 granted
    // 1000 -> Requester 3 granted
    logic [3:0] grant;


    //=====================================================
    // DUT MODE SELECTION
    //=====================================================

    // Set by the top-level testbench.
    //
    // 0 -> Fixed-priority arbiter
    // 1 -> Round-robin arbiter
    //
    // tb_fixed.sv must set:
    //     arb_if.is_rr = 1'b0;
    //
    // tb_round_robin.sv must set:
    //     arb_if.is_rr = 1'b1;
    bit is_rr;


    //=====================================================
    // COMMON ASSERTIONS
    //=====================================================
    //
    // These assertions apply to BOTH arbiters.
    //=====================================================


    // ----------------------------------------------------
    // Grant must be known and zero-hot/one-hot.
    //
    // $isunknown() detects X/Z values.
    //
    // $onehot0() allows:
    //   0000
    //   0001
    //   0010
    //   0100
    //   1000
    //
    // but rejects multi-hot values such as:
    //   0011
    //   0101
    //   1100
    // ----------------------------------------------------

    a_grant_onehot0 : assert property (
        @(posedge clk)
        disable iff (reset)
        (!$isunknown(grant) && $onehot0(grant))
    )
    else
        $error(
            "SVA: grant is unknown or not one-hot/zero-hot: grant=%b",
            grant
        );


    //=====================================================
    // FIXED-PRIORITY ARBITER ASSERTIONS
    //=====================================================
    //
    // Fixed-priority DUT is combinational.
    //
    // Priority:
    //
    // req[3] > req[2] > req[1] > req[0]
    //
    // Therefore the request and corresponding grant can
    // be checked at the same sampled clock edge.
    //
    // All fixed-priority assertions are disabled when
    // is_rr = 1.
    //=====================================================


    // ----------------------------------------------------
    // No ghost grant
    //
    // A requester may only receive a grant if that
    // requester currently has its request asserted.
    // ----------------------------------------------------

    a_fixed_no_ghost : assert property (
        @(posedge clk)
        disable iff (reset || is_rr)
        ((grant & ~req) == 4'b0000)
    )
    else
        $error(
            "SVA: Fixed arbiter granted inactive requester. req=%b grant=%b",
            req, grant
        );


    // ----------------------------------------------------
    // Work-conserving behavior
    //
    // If one or more requesters are active, the arbiter
    // must issue a grant.
    // ----------------------------------------------------

    a_fixed_work_conserving : assert property (
        @(posedge clk)
        disable iff (reset || is_rr)
        (req != 4'b0000) |-> (grant != 4'b0000)
    )
    else
        $error(
            "SVA: Fixed arbiter has request but no grant. req=%b",
            req
        );


    // ----------------------------------------------------
    // Requester 3 priority
    //
    // req[3] has the highest priority.
    //
    // Whenever req[3] is active, requester 3 must win
    // regardless of the values of req[2:0].
    // ----------------------------------------------------

    a_fixed_req3_wins : assert property (
        @(posedge clk)
        disable iff (reset || is_rr)
        req[3] |-> (grant == 4'b1000)
    )
    else
        $error(
            "SVA: Fixed-priority violation for req[3]. req=%b grant=%b",
            req, grant
        );


    // ----------------------------------------------------
    // Requester 2 priority
    //
    // Requester 2 must win whenever:
    //
    // req[3] = 0
    // req[2] = 1
    //
    // req[1:0] may have any value.
    // ----------------------------------------------------

    a_fixed_req2_wins : assert property (
        @(posedge clk)
        disable iff (reset || is_rr)
        (!req[3] && req[2])
        |-> (grant == 4'b0100)
    )
    else
        $error(
            "SVA: Fixed-priority violation for req[2]. req=%b grant=%b",
            req, grant
        );


    // ----------------------------------------------------
    // Requester 1 priority
    //
    // Requester 1 wins when requesters 3 and 2 are
    // inactive and requester 1 is active.
    // ----------------------------------------------------

    a_fixed_req1_wins : assert property (
        @(posedge clk)
        disable iff (reset || is_rr)
        (!req[3] && !req[2] && req[1])
        |-> (grant == 4'b0010)
    )
    else
        $error(
            "SVA: Fixed-priority violation for req[1]. req=%b grant=%b",
            req, grant
        );


    // ----------------------------------------------------
    // Requester 0 priority
    //
    // Requester 0 has the lowest priority.
    //
    // Therefore requesters 3, 2 and 1 must all be
    // inactive before requester 0 can receive the grant.
    // ----------------------------------------------------

    a_fixed_req0_wins : assert property (
        @(posedge clk)
        disable iff (reset || is_rr)
        (!req[3] &&
         !req[2] &&
         !req[1] &&
          req[0])
        |-> (grant == 4'b0001)
    )
    else
        $error(
            "SVA: Fixed-priority violation for req[0]. req=%b grant=%b",
            req, grant
        );


    // ----------------------------------------------------
    // Idle behavior
    //
    // If there are no active requests, no requester
    // should receive a grant.
    // ----------------------------------------------------

    a_fixed_idle_no_grant : assert property (
        @(posedge clk)
        disable iff (reset || is_rr)
        (req == 4'b0000) |-> (grant == 4'b0000)
    )
    else
        $error(
            "SVA: Fixed arbiter produced grant with no request. grant=%b",
            grant
        );


    //=====================================================
    // ROUND-ROBIN ARBITER ASSERTIONS
    //=====================================================
    //
    // IMPORTANT TIMING DIFFERENCE:
    //
    // The round-robin DUT has a REGISTERED grant.
    //
    // Therefore, the grant observed at the current edge
    // corresponds to the request sampled at the previous
    // clock edge.
    //
    // $past(req) is therefore used for RR checking.
    //
    // Xcelium 25.03 does not allow sampled-value
    // functions such as $past() without an explicit
    // clock inside "disable iff".
    //
    // Therefore:
    //
    //     disable iff (reset || !is_rr)
    //
    // contains only current signals, while previous-cycle
    // reset checks are performed inside the property.
    //=====================================================


    // ----------------------------------------------------
    // RR no ghost grant
    //
    // If reset was not active on the previous cycle,
    // every currently asserted grant bit must correspond
    // to a requester that was active on the previous
    // cycle.
    // ----------------------------------------------------

    a_rr_no_ghost : assert property (
        @(posedge clk)
        disable iff (reset || !is_rr)

        !$past(reset)
        |->
        ((grant & ~$past(req)) == 4'b0000)
    )
    else
        $error(
            "SVA: RR grant does not correspond to previous request. previous_req=%b grant=%b",
            $past(req), grant
        );


    // ----------------------------------------------------
    // RR work-conserving behavior
    //
    // If reset was inactive and at least one requester
    // was active on the previous cycle, the registered
    // grant must be non-zero.
    // ----------------------------------------------------

    a_rr_work_conserving : assert property (
        @(posedge clk)
        disable iff (reset || !is_rr)

        (!$past(reset) &&
         ($past(req) != 4'b0000))
        |->
        (grant != 4'b0000)
    )
    else
        $error(
            "SVA: RR previous request was non-zero but no grant generated. previous_req=%b",
            $past(req)
        );


    // ----------------------------------------------------
    // RR rotation under full contention
    //
    // If all four requesters continuously request access,
    // the winner must rotate.
    //
    // With req = 1111, the expected cyclic behavior is:
    //
    // 0001
    //   ->
    // 0010
    //   ->
    // 0100
    //   ->
    // 1000
    //   ->
    // 0001 ...
    //
    // This property checks that the grant does not remain
    // assigned to the same requester on consecutive
    // cycles while full contention is maintained.
    // ----------------------------------------------------

    a_rr_rotates : assert property (
        @(posedge clk)
        disable iff (reset || !is_rr)

        (!$past(reset) &&
         !$past(reset, 2) &&
         ($past(req)    == 4'hF) &&
         ($past(req, 2) == 4'hF))
        |->
        (grant != $past(grant))
    )
    else
        $error(
            "SVA: RR grant did not rotate while req=1111. grant=%b previous_grant=%b",
            grant, $past(grant)
        );


    // ----------------------------------------------------
    // RR reset behavior
    //
    // If reset was asserted on the previous sampled edge,
    // the registered round-robin grant must be cleared.
    // ----------------------------------------------------

    a_rr_reset_clears : assert property (
        @(posedge clk)
        disable iff (!is_rr)

        $past(reset)
        |->
        (grant == 4'b0000)
    )
    else
        $error(
            "SVA: RR grant was not cleared after reset. grant=%b",
            grant
        );


    //=====================================================
    // COVER PROPERTIES
    //=====================================================
    //
    // cover property does NOT indicate pass/fail.
    //
    // These properties show that useful scenarios were
    // actually exercised by the verification environment.
    //=====================================================


    // ----------------------------------------------------
    // Full contention held for four cycles
    //
    // Demonstrates that the testbench exercised all four
    // requesters simultaneously for four consecutive
    // cycles.
    //
    // This is particularly useful for exercising the
    // round-robin rotation behavior.
    // ----------------------------------------------------

    c_all_req_held : cover property (
        @(posedge clk)
        disable iff (reset)
        (req == 4'hF)[*4]
    );


    // ----------------------------------------------------
    // Idle-to-active request transition
    //
    // Covers a cycle with no request followed by a cycle
    // containing at least one request.
    // ----------------------------------------------------

    c_idle_then_req : cover property (
        @(posedge clk)
        disable iff (reset)
        (req == 4'b0000)
        ##1
        (req != 4'b0000)
    );


endinterface
