//=========================================================
// File: arbiter_if.sv
//
// Common interface used for BOTH:
//   1. Fixed-priority arbiter
//   2. Round-robin arbiter
//
// req and grant are used by both DUTs.
//
// clk and reset are required by the round-robin arbiter.
// They remain present for the fixed-priority environment
// so that the same UVM driver and monitor can be reused.
//=========================================================

interface arbiter_if(input logic clk);

    // --------------------------------------------
    // Request signal
    //
    // Each bit represents one requester.
    //
    // req[0] -> Requester 0
    // req[1] -> Requester 1
    // req[2] -> Requester 2
    // req[3] -> Requester 3
    // --------------------------------------------
    logic [3:0] req;


    // --------------------------------------------
    // Grant signal generated by the DUT.
    //
    // Expected to be one-hot or zero:
    //
    // 0000 -> No requester granted
    // 0001 -> Requester 0 granted
    // 0010 -> Requester 1 granted
    // 0100 -> Requester 2 granted
    // 1000 -> Requester 3 granted
    // --------------------------------------------
    logic [3:0] grant;


    // --------------------------------------------
    // Reset
    //
    // Used by round-robin arbiter.
    //
    // Fixed-priority arbiter does not need reset,
    // but we keep it in the common interface.
    // --------------------------------------------
    logic reset;


endinterface
